#*
#* @Author: gongluck 
#* @Date: 2020-04-02 14:55:15 
#* @Last Modified by:   gongluck 
#* @Last Modified time: 2020-04-02 14:55:15 
#*/

default:
	cd number && make
	go run main.go

clean:
	-cd number && make clean
	-rm *.a
	-rm a.out
