#*
#* @Author: gongluck 
#* @Date: 2020-04-02 14:53:52 
#* @Last Modified by:   gongluck 
#* @Last Modified time: 2020-04-02 14:53:52 
#*/

default:
	gcc -shared -o libnumber.so number.c

clean:
	-rm *.so
